apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: hello-world
spec:
  encryptedData:
    password: AgA0l1NTXvgWbELts1E3YxZYGsy1OSOzIRI3/AgaSV2EHPvz5jasjcE2UqmowUNRbxvSl0UOoWnI5gH83YbWjsl8yNPjZEXRqKQvcdxfzNEAjTJVoerqtgkhWZdHNgLZV2d5rRZtZlNrL14ZSSr2leIaRoSf1XqqoDogGO32mBsN1ZKsM/29t6MXIygFfbUYL3qh2cSpof6jFspWNM0jAbhXpzbgnu9a5TjqTZ5TCnVvICdUkC0lbM7FIh8K44fHM1WBuLvIqnB6S/+aphG5ZhNsmrsi9b1EHyvwhnBIPw4z0IJMakdLHV+cWfmbYPJ85MgvibGUDAQrA5W6ja9wVvkf9vtgMnFdlX0ISguXntBGb6h4+c0sFwIGbVWIUDQ2AAxLODw9MKvOeWn/HbTginQqp0icv9MVxWWxEbJyZCKxmWrbmsYxfciLIJEsAddP2tXBet5Mg1WZY+nR5tkPj5yqopovejZYrB4o2WOYmWrWnK8R0CYP3UjgVbMEp+3POLwqWz09Kxr6bPH6iW0JuCDmIDE7XOk31yEaT/81jH7CbwHFu//ubL5lrFUJp1MtOPllWjwyySCPgB/55uhRqcdKNGwcMSWPkcS2CKi5gbzxg+Y1ls9hc2/J15N9//GmELvAo9WHmPW5YrLDweBQ2xJabRcEZcGOU1hk7sqkt53S3qEcGEXKXWYS6UYgwgLR0rQ2MpTFjxefeTbL5jeBKw==
    username: AgA9RNTfbWlPsVNGNU4bB91s1K5Vz7fHRJuRMC6js7RQGZbbDR7yJ5QwanIARbUHdTAv9wKrD3WCyLJiwgBh4/tLl/iuoJvGvclN9yo4mIwZAv9squRwBQNoJrdMvz/5ENQYMucvDxOS3c7xNvIgSzghclT1aTavTA6JhF5RPtK+8Sydl9zF+IZF+6VgKtFRQY5N/f+9icZ/qJ2Q/lWdiPEKz+5y4x4GX/OiJJNMSFoF42QD0u2HMIO2pXdzf27dcmVzv5Wj3xl7bWO+dGojbd1uiIAN+AIphx4yOECGgFvx5+YBuQ/oTFSGxBAHbLhdlEV+QjA48SUqGaeZG5rqtjBJqps7Ig0/dg+QWX2vZeWsYElV4bOLl4VXoGFOJYrdI7gdxwG0HE2MONZ9qCTAIuVz8tbrCv0IQIXNuLJby7XHwaI8NqbCgGOgGkeT80iH/lsxV9c0aimJqD3JkrGjC5l4/LHkPr8IVkx/yv8ldHHjTL4OCUDEVhDlCsvEzdxIHu7Kdt7nzjt9Wu20bfAFBxezEFjxFtiLkjoVdC+rfwcTL72w40XGyun3E2munHqvgvX9YGntwebuK3N/fAoDvC5qx9sAWpyWuxzHLkjJGvqNvzI6FPq+Pj8oc7QF8beOh1vVO8p1uSgg/rV7s4d/swu6hKm8cWc6E7H2NX1OwtYpUtLUsBaXJ3U5CUi7ex90UWjubQuY5A==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: hello-world
---
